In [3]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
dataset_folder_path = "../../dataset"
if os.path.exists(dataset_folder_path):
    review_files = os.listdir(dataset_folder_path)

dataset2 = pd.DataFrame()

for file_name in review_files:
    file = pd.read_csv(f"{dataset_folder_path}/{file_name}",sep=',', header=0)
    random_sample = file.sample(n=3000)
    dataset2 = dataset2.append(random_sample)
    
print(dataset2.shape)

(54000, 11)

In [5]:
dataset2 = dataset2["review_text"]

In [6]:
dataset2.shape

(54000,)

In [7]:
dataset2

29049               it's a Good app that's way I give 5 Star
24825      had to write this essay even tho I didn't do n...
9586                               ChatGPT, a revolutionary.
3208                                                 Finally
13126                                            very useful
                                 ...
276331                                                  Nice
309873     Am trying to update my watsapp but its not dow...
3364821    This new update is not good at all you guys sh...
1216268    I'm probably setting I don't know how there's ...
2734043                                                  ðŸ˜ŠðŸ˜ŠðŸ˜Š
Name: review_text, Length: 54000, dtype: object

In [8]:
initial_values = [0 for _ in range(len(dataset2.values))]
dataset2 = {
    'review_text' : dataset2.values,
    "F":initial_values,
    "BR":initial_values,
    "AU":initial_values,
    "FI":initial_values,
    "IR":initial_values,
    "A":initial_values,
    "L":initial_values,
    "LF":initial_values,
    "MN":initial_values,
    "O":initial_values,
    "PE":initial_values,
    "SC":initial_values,
    "SE":initial_values,
    "US":initial_values,
    "PO":initial_values
}

In [9]:
dataset2 = pd.DataFrame(dataset2)

In [10]:
dataset2.shape
dataset2

,review_text,F,BR,AU,FI,IR,A,L,LF,MN,O,PE,SC,SE,US,PO
0,it's a Good app that's way I give 5 Star,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,had to write this essay even tho I didn't do n...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,"ChatGPT, a revolutionary.",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,Finally,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,very useful,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53995,Nice,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
53996,Am trying to update my watsapp but its not dow...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
53997,This new update is not good at all you guys sh...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
53998,I'm probably setting I don't know how there's ...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
53999,ðŸ˜ŠðŸ˜ŠðŸ˜Š,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [11]:
!mkdir output

A subdirectory or file output already exists.

In [12]:
dataset2.to_csv('output/dataset2.csv', sep=',', header=True, index=False, quotechar = '"', doublequote=True)